### ISSUE TITLE
Create new (hidden) services section

### ISSUE THREAD

**Issue by Beck89** [EnvisionMarketing/globaltech#14]
- Make a clone of this page - http://crayonsinfoway.com/demo/globaltech/services.html
- You can name it ..services2.html

Create 3 left side tabs in this order:
- Services - this content: http://globaltechdb.com/htm/turnkeydb.htm
- Construction - this content: http://globaltechdb.com/htm/construction.htm
- Consulting - this content: http://globaltechdb.com/htm/consulting.htm

Then update the three "Explore More" buttons on the homepage under services to link to these new pages.

**Comment by udittrivedi** [comment]
@Beck89 Please take a look. Thank you.
