### ISSUE TITLE
Update Main "Services" page

### ISSUE THREAD

**Issue by Beck89** [EnvisionMarketing/globaltech#17]
Basically we are combining the "hidden" services page with the one accessible from the menu

When clicking "Services" from the menu we should link to this page but remove the "2" from the URL: http://crayonsinfoway.com/demo/globaltech/services2.php

The current services page content will be moved into the new page like this:

Here is the new tab layout:
- Services Overview
- Design-Build
- Construction
- Consulting
- Aquatic Entertainment
- Guiding Principals

### Services Overview

Underneath the initial content we need to add an accordion that will contain the data from the current services page:
- Water Supply, Treatment, and Distribution Services
- Wastewater Treatment and Collection Services
- Turnkey Project Delivery Services

**Comment by udittrivedi** [comment]
I have updated the pages, please take a look. Thank you.
